function c = compute_forcing(epsilon, x, y, t)

% c = -2 + 4*epsilon^2 - 6*cos(t)^2 * (sin(x)^2 .* cos(y).^2 + ...
%     cos(2*x) .* sin(y).^2) - tan(t);

% c = -sin(x).*sin(y) .* ((2 - 4*epsilon^2)*cos(t) + sin(t) + ...
%     6*cos(t)^3 * ((sin(x).^2).*(cos(y).^2)  + ...
%     cos(2*x) .* (sin(y)).^2 ) );
% 
c = exp(-3*t) * cos(x).*cos(y) .* (exp(2*t)*(4*epsilon^2 - 3) + ...
    6*(cos(x).^2).*cos(2*y) - 6*(cos(y).^2).*sin(x).^2);
end
