function [Wq, Wq1, Wq2] = compute_Wq(u, Para)

eps = Para.epsilon;     q = Para.q;     tau = Para.tau;

% if Para.W == 0
% 
%     Wq = 0.5*(u + tau/3 + 1).^2 .* (0.5*(u + tau/3 - 1).^2 + ...
%         (2*tau/3) * (u + tau/3 - 2));
% 
%     Wq1 = u.^3 - (1 + tau^2/3)*u - 2*tau/3 * (1 + tau/3)*(1 - tau/3);
% 
%     Wq2 = 3*u.^2 - (1 + tau^2/3);
% 
% else
% 
%     Wq = (0.5*(u + 1).^2 + q * eps * (1 - sech((u + 1) / eps))) .* ...
%         (0.5*(u - 1).^2 + (tau/3) * (u - 2));
% 
%     Wq1 = (u - 1 + tau/3) .* (0.5*(u + 1).^2 + q * eps * (1 - sech((u + 1) ...
%         / eps))) + (0.5*(u - 1).^2 + (tau/3)*(u - 2)) .* (u + 1 + ...
%         q * sech((u + 1) / eps) .* tanh((u + 1) / eps));
% 
%     Wq2 = 0.5*(u + 1).^2 + q * eps * (1 - sech((u + 1) / eps)) + 2 * (u - ...
%         1 + tau/3) .* (u + 1 + q * sech((u + 1) / eps) .* tanh((u + 1) /...
%         eps)) + (0.5*(u - 1).^2 + (tau/3)*(u - 2)) .* (1 + (q/eps) * (...
%         sech((u + 1) / eps).^3 - sech((u + 1) / eps) .* ...
%         tanh((u + 1) / eps).^2));
% 
% end

Wq = (0.5*(u + 1).^2 + q * eps * (1 - sech((u + 1) / eps))) .* ...
        (0.5*(u - 1).^2 + (tau/3) * (u - 2));
    
    Wq1 = (u - 1 + tau/3) .* (0.5*(u + 1).^2 + q * eps * (1 - sech((u + 1) ...
        / eps))) + (0.5*(u - 1).^2 + (tau/3)*(u - 2)) .* (u + 1 + ...
        q * sech((u + 1) / eps) .* tanh((u + 1) / eps));
    
    Wq2 = 0.5*(u + 1).^2 + q * eps * (1 - sech((u + 1) / eps)) + 2 * (u - ...
        1 + tau/3) .* (u + 1 + q * sech((u + 1) / eps) .* tanh((u + 1) /...
        eps)) + (0.5*(u - 1).^2 + (tau/3)*(u - 2)) .* (1 + (q/eps) * (...
        sech((u + 1) / eps).^3 - sech((u + 1) / eps) .* ...
        tanh((u + 1) / eps).^2));

end